port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true
turn:
  enabled: true
  udp_port: 3478
room:
  max_participants: 12
  empty_timeout: 60
  departure_timeout: 20
logging:
  level: info
