export const PERMISSIONS = {
  admin: {
    usersView: 'Admin.Users.View',
    usersCreate: 'Admin.Users.Create',
    usersUpdate: 'Admin.Users.Update',
    usersDelete: 'Admin.Users.Delete',
    rolesView: 'Admin.Roles.View',
    rolesCreate: 'Admin.Roles.Create',
    rolesUpdate: 'Admin.Roles.Update',
    rolesDelete: 'Admin.Roles.Delete',
    permissionsView: 'Admin.Permissions.View',
    permissionsManage: 'Admin.Permissions.Manage',
    branchView: 'Admin.Branch.View',
    branchUpdate: 'Admin.Branch.Update',
  },
  rrhh: {
    employeesView: 'RRHH.Employees.View',
    employeesCreate: 'RRHH.Employees.Create',
    employeesUpdate: 'RRHH.Employees.Update',
    employeesDelete: 'RRHH.Employees.Delete',
    positionsView: 'RRHH.Positions.View',
    schedulingView: 'RRHH.Scheduling.View',
    payrollView: 'RRHH.Payroll.View',
  },
  pos: {
    ordersView: 'POS.Orders.View',
    ordersCreate: 'POS.Orders.Create',
    ordersUpdate: 'POS.Orders.Update',
    ordersCancel: 'POS.Orders.Cancel',
    kitchenView: 'POS.Kitchen.View',
    kitchenUpdate: 'POS.Kitchen.Update',
    stationsView: 'POS.Stations.View',
    stationsManage: 'POS.Stations.Manage',
    tablesView: 'POS.Tables.View',
    tablesManage: 'POS.Tables.Manage',
    tableRequestsView: 'POS.TableRequests.View',
    tableRequestsUpdate: 'POS.TableRequests.Update',
  },
  menu: {
    categoriesView: 'Menu.Categories.View',
    categoriesManage: 'Menu.Categories.Manage',
    itemsView: 'Menu.Items.View',
    itemsManage: 'Menu.Items.Manage',
  },
  inventory: {
    configView: 'Inventory.Config.View',
    configManage: 'Inventory.Config.Manage',
    articlesView: 'Inventory.Articles.View',
    articlesManage: 'Inventory.Articles.Manage',
    stockView: 'Inventory.Stock.View',
    movementsView: 'Inventory.Movements.View',
    movementsCreate: 'Inventory.Movements.Create',
  },
  purchases: {
    suppliersView: 'Purchases.Suppliers.View',
    suppliersManage: 'Purchases.Suppliers.Manage',
    ordersView: 'Purchases.Orders.View',
    ordersCreate: 'Purchases.Orders.Create',
    ordersUpdate: 'Purchases.Orders.Update',
    ordersCancel: 'Purchases.Orders.Cancel',
    ordersDelete: 'Purchases.Orders.Delete',
  },
  billing: {
    customersView: 'Billing.Customers.View',
    customersManage: 'Billing.Customers.Manage',
    cashView: 'Billing.Cash.View',
    cashOpen: 'Billing.Cash.Open',
    cashClose: 'Billing.Cash.Close',
    cashCharge: 'Billing.Cash.Charge',
    paymentMethodsView: 'Billing.PaymentMethods.View',
    paymentMethodsManage: 'Billing.PaymentMethods.Manage',
    taxView: 'Billing.Tax.View',
    taxManage: 'Billing.Tax.Manage',
    sriView: 'Billing.Sri.View',
    sriManage: 'Billing.Sri.Manage',
    sriGenerate: 'Billing.Sri.Generate',
  },
} as const;
